site_name: OAuth 2.1 Spring boot
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/eye 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/eye-outline
        name: Switch to light mode
      primary: indigo
      accent: indigo
  features:
    - content.code.copy
  icon:
    repo: fontawesome/brands/git-alt
extra_css:
  - stylesheets/extra.css

plugins:
  - search
markdown_extensions:
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

repo_url: https://github.com/m-thirumal/oauth-authorization-server
repo_name: m-thirumal/oauth-authorization-server


