spring:
  application:
    name: authorization-server
  profiles: 
    active: DEV
  main:
    #allow-bean-definition-overriding: true
    banner-mode: console
  lifecycle:
    timeout-per-shutdown-phase: 60s
server:
#  port: 9000
  shutdown: graceful
  error:
    include-stacktrace: never
    path: /error
    whitelabel:
      enabled: false
logging:
  level:
    root: INFO
    '[org.springframework.web]': INFO
    '[org.springframework.security]': INFO
    '[org.springframework.security.oauth2]': INFO
    '[in.thirumal]': debug
  file:
    path: logs
    name: logs/authorization-server.log
  logback: 
    rollingpolicy: 
      max-history: 10
      max-file-size: 100MB
      total-size-cap: 1GB
---
eureka:
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${random.int[1,999999]}
    leaseRenewalIntervalInSeconds: 10
    preferIpAddress: true
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
      user:
        name: "thirumal"
        password: "thirumal"
  client:
    region: default
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    registryFetchIntervalSeconds: 5
#Actuator
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints: 
    web: 
      exposure: 
        include: '*'
  health: 
    mail:
      enabled: false
  info:
    git:
      mode: "full"