spring:
  datasource:
    url: jdbc:postgresql://3.6.239.198:5432/authorization-1
    username: postgres
    password: Thirumal
    jdbc-url: ${spring.datasource.url} # For hikari
    hikari:
      minimum-idle: 100
      jdbc-url: ${spring.datasource.url} 
server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://thirumal:thirumal@3.6.239.198:8761/eureka/
google:
  recaptcha:
    key:
      site: 6LcTncEkAAAAACymE
      secret: 6LcTncEkAAAAAOmE5T8e
      threshold: 0.5
notification: 
  email:
    sender: no-reply@gmail.com
  sms: 
    sender: THIRU