spring:
  application:
    name: authorization-server
  profiles: 
    active: DEV
  main:
    banner-mode: console
  lifecycle:
    timeout-per-shutdown-phase: 60s
  r2dbc:
  #  name: payment
    url: r2dbc:postgresql://3.6.239.198:5432/authorization-server
    username: postgres
    password: thirumal
    pool:
      enabled: true
      initial-size: 1
      max-size: 20
      max-idle-time: 30m
server:
  port: 9000
  shutdown: graceful
  error:
    path: /error
    whitelabel:
      enabled: false
logging:
  level:
    root: INFO
    '[org.springframework.web]': INFO
    '[org.springframework.security]': debug
    '[org.springframework.security.oauth2]': debug
    '[in.thirumal]': debug
  file:
    path: logs
    name: logs/authorization-server.log
  logback: 
    rollingpolicy: 
      max-history: 10
      max-file-size: 100MB
      total-size-cap: 1GB
#Actuator
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints: 
    web: 
      exposure: 
        include: '*'
  health: 
    mail:
      enabled: false
  info:
    git:
      mode: "full"